name: Build and Test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '8'
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' 

      - name: Setup pnpm
        run: npm install -g pnpm@7

      - name: Build and Test
        run: mvn --batch-mode --update-snapshots clean package